name: CI compose
on:
  push:
    branches:
    - main
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose "docker-compose.yml" up
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot
